(feat) Bump dependencies to not conflict with tensorflow==2.0.0rc2
When installing tensorflow 2.0.0rc2 there are errors:

ERROR: thinc 6.10.3 has requirement wrapt<1.11.0,>=1.10.0, but you'll have wrapt 1.11.1 which is incompatible.
ERROR: spacy 2.0.12 has requirement regex==2017.4.5, but you'll have regex 2017.11.9 which is incompatible.